# Generated by Django 5.0.7 on 2024-08-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_remove_category_description_alter_products_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='product_id',
            new_name='product',
        ),
    ]
