# Generated by Django 5.0.7 on 2024-08-10 06:08

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_rename_product_id_variant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img1',
            field=imagekit.models.fields.ProcessedImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img4',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
