# Generated by Django 5.0.7 on 2024-08-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_alter_products_img1_alter_products_img2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='img4',
        ),
    ]
