# Generated by Django 5.0.7 on 2024-10-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_category_offer_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
