# Generated by Django 5.0.7 on 2024-08-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderedproducts_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproducts',
            name='address',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
