# Generated by Django 5.0.7 on 2024-09-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_status_orderedproducts_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('expiry_date', models.DateField()),
                ('min_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('usage_limit', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
