# Generated by Django 5.0.7 on 2024-09-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['expiry_date']},
        ),
    ]
