# Generated by Django 5.0.7 on 2024-09-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_return_request_alter_orderedproducts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproducts',
            name='return_request',
            field=models.BooleanField(default=False),
        ),
    ]
