# Generated by Django 5.0.7 on 2024-10-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproducts',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Failed', 'Failed')], null=True),
        ),
    ]
