# Generated by Django 5.0.7 on 2024-09-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_checkout_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='selcted_coupon',
            new_name='coupon',
        ),
    ]
