# Generated by Django 5.0.7 on 2024-10-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='variant_size',
            field=models.CharField(null=True),
        ),
    ]
