# Generated by Django 5.0.7 on 2024-07-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
